SELECT 
A.STOCK_ID, B.STOCK_ID, 
MONTH(A.STOCK_DATE),
AVG( A.STOCK_PRICE_HIGH*B.STOCK_PRICE_HIGH ) - ( AVG(A.STOCK_PRICE_HIGH)*AVG(B.STOCK_PRICE_HIGH) )
FROM NYSE A JOIN NYSE B 
ON A.STOCK_DATE=B.STOCK_DATE 
WHERE A.STOCK_ID < B.STOCK_ID 
AND YEAR(A.STOCK_DATE)= 2008
GROUP BY A.STOCK_ID, B. STOCK_ID,MONTH(A.STOCK_DATE);


-- For All Year and Month
SELECT 
A.STOCK_ID, B.STOCK_ID, 
MONTH(A.STOCK_DATE) STOCK_MONTH,YEAR(A.STOCK_DATE) STOCK_YEAR,
AVG( A.STOCK_PRICE_HIGH*B.STOCK_PRICE_HIGH ) - ( AVG(A.STOCK_PRICE_HIGH)*AVG(B.STOCK_PRICE_HIGH) ) COVARIANCE
FROM NYSE A JOIN NYSE B 
ON A.STOCK_DATE=B.STOCK_DATE 
WHERE A.STOCK_ID < B.STOCK_ID 
GROUP BY A.STOCK_ID, B. STOCK_ID, MONTH(A.STOCK_DATE),YEAR(A.STOCK_DATE);
